site_name: ALCF AI-Testbed
site_url: https://argonne-lcf.github.io/ALCF-AI-Testbed/
theme:
  name: material
#  font:
#    text: Proxima Nova, Montserrat, Arial
  features:
    - header.autohide
  custom_dir: overrides
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - meta
#repo_url: https://github.com/argonne-lcf/Argonne-AI-Testbed-System
nav:
    - 'About': 'https://ai.alcf.anl.gov/#about'
    - 'Testbed Applications': 'https://ai.alcf.anl.gov/#applications'
    - 'Systems': 'https://ai.alcf.anl.gov/#systems'
    - 'Cerebras (CS-1)': 'cerebras.md'
    - 'SambaNova': 'sambanova.md'
    - 'Graphcore': 'https://docs.graphcore.ai/en/latest/'
    - 'Access & Support': 'https://ai.alcf.anl.gov/#access-support'
    - Documentation: 'index.md'