site_name: Argonne AI Testbed System
theme:
  logo: assets\img\Argonne_color_white_transparent.png
  font:
    text: Proxima Nova
  features:
    - header.autohide
    - navigation.tabs
    - navigation.tabs.sticky
  name: material
  custom_dir: overrides
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
repo_url: https://github.com/argonne-lcf/Argonne-AI-Testbed-System
nav:
    - 'Back to Main Site': 'https://argonne-lcf.github.io/AITS-Site/'
    - Documentation Home: 'index.md'
    - 'About': 'https://argonne-lcf.github.io/AITS-Site/#about'
    - 'Testbed Applications': 'https://argonne-lcf.github.io/AITS-Site/#services'
    - 'Cerebras (CS-1)': 'cerebras.md'
    - 'SambaNova': 'sambanova.md'
    - 'Contact': 'https://argonne-lcf.github.io/AITS-Site/#contact'