site_name: Argonne AI Testbed System
site_url: https://argonne-lcf.github.io/Argonne-AI-Testbed-System/
theme:
  name: material
  font:
    text: Proxima Nova
  features:
    - header.autohide
  custom_dir: overrides
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
#repo_url: https://github.com/argonne-lcf/Argonne-AI-Testbed-System
nav:
    - Documentation: 'index.md'
    - 'About': 'https://argonne-lcf.github.io/AITS-Site/#about'
    - 'Testbed Applications': 'https://argonne-lcf.github.io/AITS-Site/#services'
    - 'Cerebras (CS-1)': 'cerebras.md'
    - 'SambaNova': 'sambanova.md'
    - 'Graphcore': 'https://docs.graphcore.ai/en/latest/'
    - 'Contact': 'https://argonne-lcf.github.io/AITS-Site/#contact'