header:
    title: Argonne Leadership Computing Facility
    text: AI Testbed
    button: Explore the Testbed
    buttonlink: "#services"

about:
    title: "About the AI Testbed"
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
    section: about

services:
    title: "Testbed Applications"
    text: "Lorem ipsum"
    section: services
    list:
      - title: "Deep Learning for Cancer"
        desc: "Predicting cancer type and drug response using histopathology images from the National Cancer Institute's Patient-Derived Models Repository. Image: Rick Stevens, Argonne National Laboratory"
        image: assets/img/services/Candle_300x300.png
      - title: "SARS-CoV-2 Spike Dynamics"
        desc: "AI-Driven Multiscale Simulations Illuminate Mechanisms of SARS-CoV-2 Spike Dynamics"
        image: assets/img/services/Amaro_300x300.png       
      - title: "Massive Star Simulations"
        desc: "A team of researchers from the University of California, Santa Barbara used ALCF-generated simulations to study the global structure of the gaseous outer layers of massive stars. Credit: Lars Bildsten, Kavli Institute for Theoretical Physics"
        image: assets/img/services/bildsten_300x300.png

portfolio:
    title: "Documentation"
    text: "The AI Testbed is comprised of three systems: Cerebras, Graphcore and SambaNova"
    section: portfolio
    closebutton: "Close Project"
    

#timeline:
#    title: "About" 
#    text: "Lorem ipsum timeline"
#    section: timeline
#    # left is the default
#    #start_align: "left"
#    events:
#      - title: "Our Humble Beginnings"
#        year: "2009-2011"
#        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
#        image: assets/img/timeline/1.jpg
#        alt: 
#      - title: "An Agency is Born"
#        year: "March 2011"
#        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
#        image: assets/img/timeline/2.jpg
#        alt: 
#      - title: "Jekyll Theme is created"
#        year: "2019"
#        desc: "Ravi Riley converted Agency, a Bootstrap-based theme, into a Jekyll theme. The Jekyll theme can be installed as a Ruby gem, or remotely. For more information, visit the documentation."
#        image: assets/img/timeline/3.jpg
#        alt: image alt text
#      - title: "Title"
#        year: "2009-2011"
#        desc: "Your description here, **Markdown** is fully supported."
#        image: assets/img/timeline/4.jpg
#        alt: 
#        # you can enforce the aligment
#        align: right
#    end: "Be Part <br> of Our <br> Story!"

#about:
#    title: "About Us"
#    text: "our story"
#    section: about

#clients:
#    section: clients
#    max-height: 100px
#    horizontal-scrolling: "" #"yes/no"
#    list:
#      - title: "envato"
#        url: https://github.com/raviriley/agency-jekyll-theme
#        logo: assets/img/clients/envato.jpg
#      - title: "designmodo"
#        url: https://github.com/raviriley/agency-jekyll-theme
#        logo: assets/img/clients/designmodo.jpg
#      - title: "themeforest"
#        url: https://github.com/raviriley/agency-jekyll-theme
#        logo: assets/img/clients/themeforest.jpg
#      - title: "Creative Market"
#        url: https://github.com/raviriley/agency-jekyll-theme
#        logo: assets/img/clients/creative-market.jpg
    
#team:
#    title: "OUR AMAZING TEAM"
#    text: "Lorem ipsum dolor sit amet consectetur."
#    subtext: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde. **Markdown** supported.
#    section: team
#    people:
#      - name: "Kay Garland"
#        role: "Lead Designer"
#        image: assets/img/team/500x500.jpg
#        social:
#          - url: https://twitter.com
#            icon: fab fa-twitter
#          - url: https://facebook.com
#            icon: fab fa-facebook-f
#          - url: https://linkedin.com
#            icon: fab fa-linkedin-in
#      - name: "Larry Parker"
#        role: "Lead Marketer"
#        image: assets/img/team/2.jpg
#        social:
#          - url: https://twitter.com
#            icon: fab fa-twitter
#          - url: https://facebook.com
#            icon: fab fa-facebook-f
#          - url: https://linkedin.com
#            icon: fab fa-linkedin-in
#      - name: "Diana Perterson"
#        role: "Lead Developer"
#        image: assets/img/team/500x500.jpg
#        social:
#          - url: https://twitter.com
#            icon: fab fa-twitter
#          - url: https://facebook.com
#            icon: fab fa-facebook-f
#          - url: https://linkedin.com
#            icon: fab fa-linkedin-in
          
contact:
    title: "Contact Us"
    #text: "Send testbed-related inquiries by completing the below form."
    section: contact
    
footer:
    legal: "Privacy Policy"
    social:
      - url: https://twitter.com
        icon: "fab fa-twitter"  
      - url: https://facebook.com
        icon: "fab fa-facebook-f"
      - url: https://linkedin.com
        icon: "fab fa-linkedin-in"
      - url: https://github.com/raviriley/agency-jekyll-theme
        icon: "fab fa-github"
      - url: https://instagram.com
        icon: "fab fa-instagram"


# {{ site.data.sitetext.ex.ex | markdownify | default: example }}
